project_id = "pzlkkbxwvsvefkhzkeel"

[functions.analyze-company-website]
verify_jwt = false

[functions.generate-job-description]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false